"""HTTP Headers constants."""

CONNECTION = 'CONNECTION'
CONTENT_DISPOSITION = 'CONTENT-DISPOSITION'
CONTENT_ENCODING = 'CONTENT-ENCODING'
CONTENT_LENGTH = 'CONTENT-LENGTH'
CONTENT_TRANSFER_ENCODING = 'CONTENT-TRANSFER-ENCODING'
CONTENT_TYPE = 'CONTENT-TYPE'
